
// This file was auto-generated by ML.NET Model Builder. 

using System;

namespace SampleRegression.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            SampleRegression.ModelInput sampleData = new SampleRegression.ModelInput()
            {
                Year = 2014F,
                Mileage = 35725F,
                City = @"El Paso",
                State = @"TX",
                Vin = @"19VDE2E53EE000083",
                Make = @"Acura",
                Model = @"ILX6-Speed",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = SampleRegression.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");


            Console.WriteLine($"Price: {8995F}");
            Console.WriteLine($"Year: {2014F}");
            Console.WriteLine($"Mileage: {35725F}");
            Console.WriteLine($"City: {@"El Paso"}");
            Console.WriteLine($"State: {@"TX"}");
            Console.WriteLine($"Vin: {@"19VDE2E53EE000083"}");
            Console.WriteLine($"Make: {@"Acura"}");
            Console.WriteLine($"Model: {@"ILX6-Speed"}");


            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
