// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SampleRegression.ConsoleApp
{
    public partial class SampleRegression
    {
        /// <summary>
        /// model input class for SampleRegression.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Year")]
            public float Year { get; set; }

            [ColumnName(@"Mileage")]
            public float Mileage { get; set; }

            [ColumnName(@"City")]
            public string City { get; set; }

            [ColumnName(@"State")]
            public string State { get; set; }

            [ColumnName(@"Vin")]
            public string Vin { get; set; }

            [ColumnName(@"Make")]
            public string Make { get; set; }

            [ColumnName(@"Model")]
            public string Model { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SampleRegression.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Price")]
            public float Price { get; set; }

            [ColumnName(@"Year")]
            public float Year { get; set; }

            [ColumnName(@"Mileage")]
            public float Mileage { get; set; }

            [ColumnName(@"City")]
            public float[] City { get; set; }

            [ColumnName(@"State")]
            public float[] State { get; set; }

            [ColumnName(@"Vin")]
            public float[] Vin { get; set; }

            [ColumnName(@"Make")]
            public float[] Make { get; set; }

            [ColumnName(@"Model")]
            public float[] Model { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SampleRegression.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
